default_language_version:
  python: python3.9
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-quotes
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args:
    - --balanced
    - --check-only
    - --virtual-env=env
    files: '\.py$'
